<?php

namespace App\HttpController;

use App\Model\Users;
use App\Utility\RedisService;
use EasySwoole\Core\Http\AbstractInterface\Controller;

/**
 * Class Index
 * @package App\HttpController
 */
class Index extends Controller
{
    /**
     * 首页方法
     * @author : evalor <master@evalor.cn>
     */
    function index()
    {
        $redis = RedisService::getInstance();

        $this->response()->write(json_encode(['hello, world']));
    }

    function test1()
    {
        $this->response()->write('this is a test');
    }

    function actionNotFound($action): void
    {
        parent::actionNotFound($action); // TODO: Change the autogenerated stub
        $this->response()->write('there is no action');
    }

    private function addUser(array $userInfo)
    {
        $user = new Users();
        $user->user_name = $userInfo['name'];
        $user->password = md5($userInfo['name']);
        $user->save();
        var_dump(111);
    }
}